# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
    paths:
      - project-a/**

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Echo project name
        run: echo package-a
